### ISSUE TITLE
tape added to buckets

### ISSUE THREAD

**Issue by zacrook** [Multiplanetary-Innovation-Enterprise/trencher#104]
visibility tape for bucket video
Back rounded edge and connected edge to chain

**Comment by gmtenbro** [comment]
After my conversation with Marcello, I am going to use the black and yellow tape on only the sides of the bucket to improve visibility. The buckets will also be numbered with a sharpie to keep track of which one is which. Ideally when the chain is full the buckets will go in numerical order.
