### ISSUE TITLE
Measure volume of regolith cart

### ISSUE THREAD

**Issue by colinsch** [Multiplanetary-Innovation-Enterprise/trencher#137]
measure the volume of the section that will be filled with regolith, need this to estimate the bulk density of regolith
Make marks in cart to help determine where the regolith will lie

**Comment by gmtenbro** [comment]
[Divider Dimensions.pdf](https://github.com/Multiplanetary-Innovation-Enterprise/trencher/files/8356314/Divider.Dimensions.pdf)

This document shows the measured dimensions of the interior of the regolith cart. Regolith height should be between 9.5 and 10.5 inches, so 1 to 2 inches from the top of the divider.
