### ISSUE TITLE
Change Chain Length and Bucket config

### ISSUE THREAD

**Issue by zacrook** [Multiplanetary-Innovation-Enterprise/trencher#36]
Change chain and bucket spacing so that it works with short config

**Comment by gmtenbro** [comment]
Vacuum chamber set-up requires 86 chain links, 11 buckets, and this is achieved by using 10 sets of 8 links and 1 set of 6 links, per the previous end of semester report.

**Comment by gmtenbro** [comment]
The chain has been changed to the correct length but I'm not sure if it made it on the trencher. @zacrook Any idea if the chain is on or not?
